// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: secGoods.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecGoods struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price        string `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock        int64  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	Photo        string `protobuf:"bytes,5,opt,name=photo,proto3" json:"photo,omitempty"`
	Content      string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	SecKillStart int64  `protobuf:"varint,7,opt,name=secKillStart,proto3" json:"secKillStart,omitempty"`
	SecKillEnd   int64  `protobuf:"varint,8,opt,name=secKillEnd,proto3" json:"secKillEnd,omitempty"`
}

func (x *SecGoods) Reset() {
	*x = SecGoods{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secGoods_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecGoods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecGoods) ProtoMessage() {}

func (x *SecGoods) ProtoReflect() protoreflect.Message {
	mi := &file_secGoods_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecGoods.ProtoReflect.Descriptor instead.
func (*SecGoods) Descriptor() ([]byte, []int) {
	return file_secGoods_proto_rawDescGZIP(), []int{0}
}

func (x *SecGoods) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecGoods) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecGoods) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *SecGoods) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *SecGoods) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *SecGoods) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SecGoods) GetSecKillStart() int64 {
	if x != nil {
		return x.SecKillStart
	}
	return 0
}

func (x *SecGoods) GetSecKillEnd() int64 {
	if x != nil {
		return x.SecKillEnd
	}
	return 0
}

type SecGoodsId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SecGoodsId) Reset() {
	*x = SecGoodsId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secGoods_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecGoodsId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecGoodsId) ProtoMessage() {}

func (x *SecGoodsId) ProtoReflect() protoreflect.Message {
	mi := &file_secGoods_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecGoodsId.ProtoReflect.Descriptor instead.
func (*SecGoodsId) Descriptor() ([]byte, []int) {
	return file_secGoods_proto_rawDescGZIP(), []int{1}
}

func (x *SecGoodsId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_secGoods_proto protoreflect.FileDescriptor

var file_secGoods_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x65, 0x63, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0xce, 0x01, 0x0a, 0x08, 0x53, 0x65, 0x63, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x63, 0x4b, 0x69, 0x6c,
	0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x4b, 0x69, 0x6c,
	0x6c, 0x45, 0x6e, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x63, 0x4b,
	0x69, 0x6c, 0x6c, 0x45, 0x6e, 0x64, 0x22, 0x1c, 0x0a, 0x0a, 0x53, 0x65, 0x63, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x32, 0x43, 0x0a, 0x0e, 0x53, 0x65, 0x63, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x79, 0x49, 0x64, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x65, 0x63, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x1a, 0x0d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x65, 0x63, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_secGoods_proto_rawDescOnce sync.Once
	file_secGoods_proto_rawDescData = file_secGoods_proto_rawDesc
)

func file_secGoods_proto_rawDescGZIP() []byte {
	file_secGoods_proto_rawDescOnce.Do(func() {
		file_secGoods_proto_rawDescData = protoimpl.X.CompressGZIP(file_secGoods_proto_rawDescData)
	})
	return file_secGoods_proto_rawDescData
}

var file_secGoods_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_secGoods_proto_goTypes = []interface{}{
	(*SecGoods)(nil),   // 0: api.SecGoods
	(*SecGoodsId)(nil), // 1: api.SecGoodsId
}
var file_secGoods_proto_depIdxs = []int32{
	1, // 0: api.SecGoodsServer.GetSecGoodsById:input_type -> api.SecGoodsId
	0, // 1: api.SecGoodsServer.GetSecGoodsById:output_type -> api.SecGoods
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_secGoods_proto_init() }
func file_secGoods_proto_init() {
	if File_secGoods_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_secGoods_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecGoods); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secGoods_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecGoodsId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_secGoods_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secGoods_proto_goTypes,
		DependencyIndexes: file_secGoods_proto_depIdxs,
		MessageInfos:      file_secGoods_proto_msgTypes,
	}.Build()
	File_secGoods_proto = out.File
	file_secGoods_proto_rawDesc = nil
	file_secGoods_proto_goTypes = nil
	file_secGoods_proto_depIdxs = nil
}
