// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v3.20.1
// source: secGoods.proto

package api

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// SecGoodsServerClient is the client API for SecGoodsServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecGoodsServerClient interface {
	GetSecGoodsById(ctx context.Context, in *SecGoodsId, opts ...grpc_go.CallOption) (*SecGoods, common.ErrorWithAttachment)
}

type secGoodsServerClient struct {
	cc *triple.TripleConn
}

type SecGoodsServerClientImpl struct {
	GetSecGoodsById func(ctx context.Context, in *SecGoodsId) (*SecGoods, error)
}

func (c *SecGoodsServerClientImpl) GetDubboStub(cc *triple.TripleConn) SecGoodsServerClient {
	return NewSecGoodsServerClient(cc)
}

func (c *SecGoodsServerClientImpl) XXX_InterfaceName() string {
	return "api.SecGoodsServer"
}

func NewSecGoodsServerClient(cc *triple.TripleConn) SecGoodsServerClient {
	return &secGoodsServerClient{cc}
}

func (c *secGoodsServerClient) GetSecGoodsById(ctx context.Context, in *SecGoodsId, opts ...grpc_go.CallOption) (*SecGoods, common.ErrorWithAttachment) {
	out := new(SecGoods)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GetSecGoodsById", in, out)
}

// SecGoodsServerServer is the server API for SecGoodsServer service.
// All implementations must embed UnimplementedSecGoodsServerServer
// for forward compatibility
type SecGoodsServerServer interface {
	GetSecGoodsById(context.Context, *SecGoodsId) (*SecGoods, error)
	mustEmbedUnimplementedSecGoodsServerServer()
}

// UnimplementedSecGoodsServerServer must be embedded to have forward compatible implementations.
type UnimplementedSecGoodsServerServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedSecGoodsServerServer) GetSecGoodsById(context.Context, *SecGoodsId) (*SecGoods, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecGoodsById not implemented")
}
func (s *UnimplementedSecGoodsServerServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedSecGoodsServerServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedSecGoodsServerServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &SecGoodsServer_ServiceDesc
}
func (s *UnimplementedSecGoodsServerServer) XXX_InterfaceName() string {
	return "api.SecGoodsServer"
}

func (UnimplementedSecGoodsServerServer) mustEmbedUnimplementedSecGoodsServerServer() {}

// UnsafeSecGoodsServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecGoodsServerServer will
// result in compilation errors.
type UnsafeSecGoodsServerServer interface {
	mustEmbedUnimplementedSecGoodsServerServer()
}

func RegisterSecGoodsServerServer(s grpc_go.ServiceRegistrar, srv SecGoodsServerServer) {
	s.RegisterService(&SecGoodsServer_ServiceDesc, srv)
}

func _SecGoodsServer_GetSecGoodsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecGoodsId)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GetSecGoodsById", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// SecGoodsServer_ServiceDesc is the grpc_go.ServiceDesc for SecGoodsServer service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecGoodsServer_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "api.SecGoodsServer",
	HandlerType: (*SecGoodsServerServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "GetSecGoodsById",
			Handler:    _SecGoodsServer_GetSecGoodsById_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "secGoods.proto",
}
